services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - /home/alex/jellyfin-config:/config
      - /home/alex/jellyfin-cache:/cache
      - type: bind
        source: /mnt/TV
        target: /TV
      - type: bind
        source: /mnt/Films
        target: /Films
      - type: bind
        source: /mnt/Music
        target: /Music
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      tailscale_default-bitesized:
        ipv4_address: 172.30.0.5
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: 'unless-stopped'
volumes:
  Media:
    external: true

networks:
  tailscale_default-bitesized:
    external: true

