services:
  pihole-internal:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - 9800:80
    environment:
      TZ: 'Europe/Helsinki'
      WEBPASSWORD: <password>
    volumes:
      - /home/alex/internal-pihole/etc-pihole:/etc/pihole
      - /home/alex/internal-pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
